CREATE OR ALTER PROCEDURE [dbo].[EstadosDinamicosDefaultsSearch]
@IdCuenta INT = 0
AS
BEGIN

INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL0','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL1','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL2','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL3','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL4','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL5','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL6','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL7','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL8','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','AL9','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','ALA','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 2 Verde Fijo','ALB','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','ALC','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','ALD','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 1 rojo destellando','ALE','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador1','Cambio a estado 2 Verde Fijo','ALF','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 2 trasparente','AL0','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 2 trasparente','AL1','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 2 trasparente','AL2','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 2 trasparente','AL3','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 1 amarillo Fijo','AL4','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 1 amarillo Fijo','AL5','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 1 amarillo Fijo','AL6','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 1 amarillo Fijo','AL7','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 2 trasparente','AL8','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 2 trasparente','AL9','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 2 trasparente','ALA','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 2 trasparente','ALB','2','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 1 amarillo Fijo','ALC','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 1 amarillo Fijo','ALD','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 1 amarillo Fijo','ALE','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('Indicador2','Cambio a estado 1 amarillo Fijo','ALF','1','','1','1',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('ALARIE1','ALARI entrada 1 valor 0','AL0,AL2,AL4,AL6,AL8,ALA,ALC,ALE','0','','1','0',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('ALARIE1','ALARI entrada 1 valor 1','AL1,AL3,AL5,AL7,AL9,ALB,ALD,ALF','1','','1','0',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('ALARIE2','ALARI entrada 2 valor 0','AL0,AL1,AL4,AL5,AL8,AL9,ALC,ALD','0','','1','0',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('ALARIE2','ALARI entrada 2 valor 1','AL2,AL3,AL6,AL7,ALA,ALB,ALE,ALF','1','','1','0',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('ALARIE3','ALARI entrada 3 valor 0','AL0,AL1,AL2,AL3,AL8,AL9,ALA,ALB','0','','1','0',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('ALARIE3','ALARI entrada 3 valor 1','AL4,AL5,AL6,AL7,ALC,ALD,ALE,ALF','1','','1','0',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('ALARIE4','ALARI entrada 4 valor 0','AL0,AL1,AL2,AL3,AL4,AL5,AL6,AL7','0','','1','0',@IdCuenta)
INSERT INTO _tablas.dbo.t_estadosdinamicos([ted_cCodigo],[ted_cDescripcion],[ted_cEventos],[ted_iValor],[ted_iPorUsuario],[ted_iActivo],[ted_iEditable],[ted_idCta])VALUES('ALARIE4','ALARI entrada 4 valor 1','AL8,AL9,ALA,ALB,ALC,ALD,ALE,ALF','1','','1','0',@IdCuenta)



END