CREATE OR ALTER PROCEDURE [dbo].[SearchLandingConfig]
    @lcfg_iid CHAR = '0',
    @page INT = 1,
    @start INT = 0,
    @limit INT = 50,
    @sort VARCHAR(256) = '',
    @group VARCHAR(256) = '',
    @filter VARCHAR(2048) = '',
    @_dc VARCHAR(256) = '',
    @totalrows INT = 1 OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    print @lcfg_iid;
    DECLARE @sql NVARCHAR(MAX);
    SET @sql =
		N'SELECT
		lcfg_iid,
		lcfg_cname,
		JSON_VALUE(lcfg_ccontent, ''$.mostrarPais'') AS mostrarPais,
		JSON_VALUE(lcfg_ccontent, ''$.mostrarProvincia'') AS mostrarProvincia,
		JSON_VALUE(lcfg_ccontent, ''$.step2LabelProvincia'') AS step2LabelProvincia,
		JSON_VALUE(lcfg_ccontent, ''$.mostrarFecNac'') AS mostrarFecNac,
		JSON_VALUE(lcfg_ccontent, ''$.lcfg_iid'') AS lcfg_iid_json,
		JSON_VALUE(lcfg_ccontent, ''$.principalServer'') AS principalServer,
		JSON_VALUE(lcfg_ccontent, ''$.nombreForm'') AS nombreForm,
		JSON_VALUE(lcfg_ccontent, ''$.Dealer'') AS Dealer,
		JSON_VALUE(lcfg_ccontent, ''$.nombreCampoDealer'') AS nombreCampoDealer,
		JSON_VALUE(lcfg_ccontent, ''$.solicitarCodigoActivacion'') AS solicitarCodigoActivacion,
		JSON_VALUE(lcfg_ccontent, ''$.codigoActivacion'') AS codigoActivacion,
		JSON_VALUE(lcfg_ccontent, ''$.groupMax'') AS groupMax,
		JSON_VALUE(lcfg_ccontent, ''$.MailTo'') AS MailTo,
		JSON_VALUE(lcfg_ccontent, ''$.MailSubject'') AS MailSubject,
		JSON_VALUE(lcfg_ccontent, ''$.MailBodyNO'') AS MailBodyNO,
		JSON_VALUE(lcfg_ccontent, ''$.MailSubjectCustomer'') AS MailSubjectCustomer,
		JSON_VALUE(lcfg_ccontent, ''$.MailBodyCustomer'') AS MailBodyCustomer,
		JSON_VALUE(lcfg_ccontent, ''$.reCaptcha'') AS reCaptcha,
		JSON_VALUE(lcfg_ccontent, ''$.condiciones'') AS condiciones,
		JSON_VALUE(lcfg_ccontent, ''$.plantillaSP'') AS plantillaSP,
		JSON_VALUE(lcfg_ccontent, ''$.automonitoreo'') AS automonitoreo,
		JSON_VALUE(lcfg_ccontent, ''$.apptype'') AS apptype,
		JSON_VALUE(lcfg_ccontent, ''$.diasPruebaCampo'') AS diasPruebaCampo,
		JSON_VALUE(lcfg_ccontent, ''$.diasprueba'') AS diasprueba,
		JSON_VALUE(lcfg_ccontent, ''$.cuentatipo'') AS cuentatipo,
		JSON_VALUE(lcfg_ccontent, ''$.enviarEmail'') AS enviarEmail ,
		JSON_VALUE(lcfg_ccontent, ''$.emailContactoAyuda'') AS emailContactoAyuda,
		JSON_VALUE(lcfg_ccontent, ''$.imei'') AS imei,
		JSON_VALUE(lcfg_ccontent, ''$.mostrarMensaje'') AS mostrarMensaje,
		JSON_VALUE(lcfg_ccontent, ''$.ocultarPregunta'') AS ocultarPregunta,
		JSON_VALUE(lcfg_ccontent, ''$.mailSubjectActiveAccount'') AS mailSubjectActiveAccount,
		JSON_VALUE(lcfg_ccontent, ''$.mailBodyActiveAccount'') AS mailBodyActiveAccount,
		JSON_VALUE(lcfg_ccontent, ''$.emailsTemplates'') AS emailsTemplates,
		JSON_VALUE(lcfg_ccontent, ''$.nombreApp'') AS nombreApp,
		JSON_VALUE(lcfg_ccontent, ''$.autoActivarSP'') AS autoActivarSP,
		JSON_VALUE(lcfg_ccontent, ''$.esLandingAcotada'') AS esLandingAcotada,
		JSON_VALUE(lcfg_ccontent, ''$.demo'') AS demo,
		JSON_VALUE(lcfg_ccontent, ''$.activarPago'') AS activarPago,
		JSON_VALUE(lcfg_ccontent, ''$.DealerFreemium'') AS DealerFreemium,
		JSON_VALUE(lcfg_ccontent, ''$.activarFreemium'') AS activarFreemium,
		JSON_VALUE(lcfg_ccontent, ''$.textoInvitaPagar'') AS textoInvitaPagar,
		JSON_VALUE(lcfg_ccontent, ''$.tituloRegistroFreemium'') AS tituloRegistroFreemium,
		JSON_VALUE(lcfg_ccontent, ''$.textoRegistroFreemium'') AS textoRegistroFreemium,
		JSON_VALUE(lcfg_ccontent, ''$.textoBotonFreemium'') AS textoBotonFreemium,
		JSON_VALUE(lcfg_ccontent, ''$.errorFreemium'') AS errorFreemium,
		JSON_VALUE(lcfg_ccontent, ''$.errorActivacion'') AS errorActivacion,
		JSON_VALUE(lcfg_ccontent, ''$.Public_Key'') AS Public_Key,
		JSON_VALUE(lcfg_ccontent, ''$.Access_Token'') AS Access_Token,
		JSON_VALUE(lcfg_ccontent, ''$.preapproval_plan_id_mensual'') AS preapproval_plan_id_mensual,
		JSON_VALUE(lcfg_ccontent, ''$.preapproval_plan_id_anual'') AS preapproval_plan_id_anual,
		JSON_VALUE(lcfg_ccontent, ''$.clientId'') AS clientId,
		JSON_VALUE(lcfg_ccontent, ''$._clientId'') AS _clientId,
		JSON_VALUE(lcfg_ccontent, ''$.clientSecret'') AS clientSecret,
		JSON_VALUE(lcfg_ccontent, ''$.plan_id_mensual_paypal'') AS plan_id_mensual_paypal,
		JSON_VALUE(lcfg_ccontent, ''$.plan_id_anual_paypal'') AS plan_id_anual_paypal,
		JSON_VALUE(lcfg_ccontent, ''$.textoConfiramaPagoFreemium'') AS textoConfiramaPagoFreemium,
		JSON_VALUE(lcfg_ccontent, ''$.textoConfiramaPagoComun'') AS textoConfiramaPagoComun,
		JSON_VALUE(lcfg_ccontent, ''$.btnVolver'') AS btnVolver,
		JSON_VALUE(lcfg_ccontent, ''$.lblFaltaImei'') AS lblFaltaImei,
		JSON_VALUE(lcfg_ccontent, ''$.textoInicio'') AS textoInicio,
		JSON_VALUE(lcfg_ccontent, ''$.lblTituloForm'') AS lblTituloForm,
		JSON_VALUE(lcfg_ccontent, ''$.imeiValidated'') AS imeiValidated,
		JSON_VALUE(lcfg_ccontent, ''$.pagoPendienteTitulo'') AS pagoPendienteTitulo,
		JSON_VALUE(lcfg_ccontent, ''$.pagoPendienteSubTitulo'') AS pagoPendienteSubTitulo,
		JSON_VALUE(lcfg_ccontent, ''$.pagoPendienteBajadaLinea'') AS pagoPendienteBajadaLinea,
		JSON_VALUE(lcfg_ccontent, ''$.pagoPendienteTextoBoton'') AS pagoPendienteTextoBoton,
		JSON_VALUE(lcfg_ccontent, ''$.btnCancelarPago'') AS btnCancelarPago,
		JSON_VALUE(lcfg_ccontent, ''$.errorValidatePending'') AS errorValidatePending,
		JSON_VALUE(lcfg_ccontent, ''$.lblTextoCodPromocional'') AS lblTextoCodPromocional,
		JSON_VALUE(lcfg_ccontent, ''$.planTitulo'') AS planTitulo,
		JSON_VALUE(lcfg_ccontent, ''$.theme'') AS theme ,
		JSON_VALUE(lcfg_ccontent, ''$.step1Placeholder'') AS step1Placeholder,
		JSON_VALUE(lcfg_ccontent, ''$.step1ShowErrorCodigoTexto1'') AS step1ShowErrorCodigoTexto1,
		JSON_VALUE(lcfg_ccontent, ''$.step1ShowErrorCodigoTexto2'') AS step1ShowErrorCodigoTexto2,
		JSON_VALUE(lcfg_ccontent, ''$.txtBtnSiguiente'') AS txtBtnSiguiente,
		JSON_VALUE(lcfg_ccontent, ''$.txtBtnAnterior'') AS txtBtnAnterior,
		JSON_VALUE(lcfg_ccontent, ''$.step2BtnYaTengoCta'') AS step2BtnYaTengoCta,
		JSON_VALUE(lcfg_ccontent, ''$.step2BtnSoyUsuario'') AS step2BtnSoyUsuario,
		JSON_VALUE(lcfg_ccontent, ''$.step2TituloDatosPersonales'') AS step2TituloDatosPersonales,
		JSON_VALUE(lcfg_ccontent, ''$.step2PlaceHolderNombre'') AS step2PlaceHolderNombre,
		JSON_VALUE(lcfg_ccontent, ''$.step2ShowErrorNombre'') AS step2ShowErrorNombre,
		JSON_VALUE(lcfg_ccontent, ''$.step2PlaceHolderDireccion'') AS step2PlaceHolderDireccion,
		JSON_VALUE(lcfg_ccontent, ''$.step2ShowErrorDireccion'') AS step2ShowErrorDireccion,
		JSON_VALUE(lcfg_ccontent, ''$.step3Titulo'') AS step3Titulo,
		JSON_VALUE(lcfg_ccontent, ''$.step3PlaceHolderEmail'') AS step3PlaceHolderEmail,
		JSON_VALUE(lcfg_ccontent, ''$.step3ShowErrorEmail'') AS step3ShowErrorEmail,
		JSON_VALUE(lcfg_ccontent, ''$.step3ShowLabelErrorFormatMail'') AS step3ShowLabelErrorFormatMail,
		JSON_VALUE(lcfg_ccontent, ''$.step3ShowLabelErrorExisteMail'') AS step3ShowLabelErrorExisteMail,
		JSON_VALUE(lcfg_ccontent, ''$.step3PlaceHolderConfirmaMail'') AS step3PlaceHolderConfirmaMail,
		JSON_VALUE(lcfg_ccontent, ''$.step3ShowLabelErrorConfirmaMail'') AS step3ShowLabelErrorConfirmaMail,
		JSON_VALUE(lcfg_ccontent, ''$.step3showLabelErrorFormatConfirmaMail'') AS step3showLabelErrorFormatConfirmaMail,
		JSON_VALUE(lcfg_ccontent, ''$.step3ShowLabelErrorCompareMail'') AS step3ShowLabelErrorCompareMail,
		JSON_VALUE(lcfg_ccontent, ''$.step3showLabelErrorTel'') AS step3showLabelErrorTel,
		JSON_VALUE(lcfg_ccontent, ''$.step3PlaceHolderTel'') AS step3PlaceHolderTel,
		JSON_VALUE(lcfg_ccontent, ''$.step3showLabelErrorLongTel'') AS step3showLabelErrorLongTel,
		JSON_VALUE(lcfg_ccontent, ''$.step3showLabelErrorExisteTel'') AS step3showLabelErrorExisteTel,
		JSON_VALUE(lcfg_ccontent, ''$.step3showLabelErrorConfirmaTel'') AS step3showLabelErrorConfirmaTel,
		JSON_VALUE(lcfg_ccontent, ''$.step3showLabelErrorConfirmaLongTel'') AS step3showLabelErrorConfirmaLongTel,
		JSON_VALUE(lcfg_ccontent, ''$.step3showLabelErrorCompareTel'') AS step3showLabelErrorCompareTel,
		JSON_VALUE(lcfg_ccontent, ''$.step4TituloVerificarDatos'') AS step4TituloVerificarDatos,
		JSON_VALUE(lcfg_ccontent, ''$.step4LabelNombre'') AS step4LabelNombre,
		JSON_VALUE(lcfg_ccontent, ''$.step4LabelDireccion'') AS step4LabelDireccion,
		JSON_VALUE(lcfg_ccontent, ''$.step4LabelPais'') AS step4LabelPais,
		JSON_VALUE(lcfg_ccontent, ''$.step4LabelTelefono'') AS step4LabelTelefono,
		JSON_VALUE(lcfg_ccontent, ''$.step4LabelMail'') AS step4LabelMail,
		JSON_VALUE(lcfg_ccontent, ''$.step4btnVolver'') AS step4btnVolver,
		JSON_VALUE(lcfg_ccontent, ''$.step4btnEnviar'') AS step4btnEnviar,
		JSON_VALUE(lcfg_ccontent, ''$.mensajeVerificaionExitosa'') AS mensajeVerificaionExitosa,
		JSON_VALUE(lcfg_ccontent, ''$.step3PlaceHolderConfirmaTel'') AS step3PlaceHolderConfirmaTel,
		JSON_VALUE(lcfg_ccontent, ''$.step1MayorDeEdad'') AS step1MayorDeEdad,
		JSON_VALUE(lcfg_ccontent, ''$.step2Localidad'') AS step2Localidad,
		JSON_VALUE(lcfg_ccontent, ''$.step4FecNac'') AS step4FecNac,
		JSON_VALUE(lcfg_ccontent, ''$.step4Provincia'') AS step4Provincia,
		JSON_VALUE(lcfg_ccontent, ''$.steepOtrosActivar'') AS steepOtrosActivar,
		JSON_VALUE(lcfg_ccontent, ''$.step1CuentaYTelefono'') AS step1CuentaYTelefono,
		JSON_VALUE(lcfg_ccontent, ''$.step1CuentaYClave'') AS step1CuentaYClave,
		JSON_VALUE(lcfg_ccontent, ''$.step1NroCta'') AS step1NroCta,
		JSON_VALUE(lcfg_ccontent, ''$.step1DatosErroneos'') AS step1DatosErroneos,
		JSON_VALUE(lcfg_ccontent, ''$.step1IngreseClave'') AS step1IngreseClave,
		JSON_VALUE(lcfg_ccontent, ''$.violenciagenero'') AS violenciagenero,
		JSON_VALUE(lcfg_ccontent, ''$.dealerViolenciagenero'') AS dealerViolenciagenero,
		JSON_VALUE(lcfg_ccontent, ''$.campoDiscapacidad'') AS campoDiscapacidad,
		JSON_VALUE(lcfg_ccontent, ''$.step2ViolenciaGenero'') AS step2ViolenciaGenero,
		JSON_VALUE(lcfg_ccontent, ''$.step2Discapacidad'') AS step2Discapacidad,
		JSON_VALUE(lcfg_ccontent, ''$.step2Obs'') AS step2Obs,
		JSON_VALUE(lcfg_ccontent, ''$.step2PlaceholderCustom'') AS step2PlaceholderCustom,
		JSON_VALUE(lcfg_ccontent, ''$.campoObs'') AS campoObs,
		JSON_VALUE(lcfg_ccontent, ''$.labelCustom'') AS labelCustom,
		JSON_VALUE(lcfg_ccontent, ''$.mostrarDNI'') AS mostrarDNI,
		JSON_VALUE(lcfg_ccontent, ''$.tiposDNI'') AS tiposDNI,
		JSON_VALUE(lcfg_ccontent, ''$.defaultOptionPais'') AS defaultOptionPais,
		JSON_VALUE(lcfg_ccontent, ''$.defaultOptionProvincia'') AS defaultOptionProvincia,

		JSON_VALUE(lcfg_ccontent, ''$.keycontrol'') AS keycontrol,
		JSON_VALUE(lcfg_ccontent, ''$.beaerToken'') AS beaerToken,
		JSON_VALUE(lcfg_ccontent, ''$.msjvalidacion'') AS msjvalidacion,

		JSON_VALUE(lcfg_ccontent, ''$.validarTelefonoWhatsapp'') AS validarTelefonoWhatsapp,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappTituloModal'') AS whatsappTituloModal,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappSubtituloModal'') AS whatsappSubtituloModal,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappPlaceholderCodigo'') AS whatsappPlaceholderCodigo,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappBtnEnviarCodigo'') AS whatsappBtnEnviarCodigo,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappBtnValidar'') AS whatsappBtnValidar,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappBtnReenviar'') AS whatsappBtnReenviar,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappErrorCodigoVacio'') AS whatsappErrorCodigoVacio,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappErrorCodigoInvalido'') AS whatsappErrorCodigoInvalido,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappMensajeEnviado'') AS whatsappMensajeEnviado,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappMensajeReenviado'') AS whatsappMensajeReenviado,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappEnviandoCodigo'') AS whatsappEnviandoCodigo,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappValidando'') AS whatsappValidando,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappCodigoValidado'') AS whatsappCodigoValidado,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappErrorEnvio'') AS whatsappErrorEnvio,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappValidezCodigo'') AS whatsappValidezCodigo,
		JSON_VALUE(lcfg_ccontent, ''$.whatsappMensajeInicial'') AS whatsappMensajeInicial,
		JSON_VALUE(lcfg_ccontent, ''$.autocompletarDireccion'') AS autocompletarDireccion,
		JSON_VALUE(lcfg_ccontent, ''$.caracteristicaDefault'') AS caracteristicaDefault,
		JSON_VALUE(lcfg_ccontent, ''$.paisAutocompletarDireccion'') AS paisAutocompletarDireccion
	FROM
		_Datos..LandingConfig
	';
    IF @lcfg_iid > 0
	BEGIN
		SET @sql += ' WHERE lcfg_iid=' + @lcfg_iid;
	END
	print @sql;
    EXEC sp_executesql @sql;
END;