CREATE OR ALTER PROCEDURE [dbo].[SearchLandingConfigAnt]
	-- Parametros para verificacion
 @nombre VARCHAR(50) = '',
 @dealer VARCHAR(50) = '',
 @page INT = 1,
 @start INT = 0,
 @limit INT = 50,
 @sort VARCHAR(256) = '',
 @group VARCHAR(256) = '',
 @filter VARCHAR(2048) = '',
 @_dc VARCHAR(256) = '',
 @totalrows INT = 1 OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	IF @nombre = ''
	BEGIN
		DECLARE @json VARCHAR(MAX)
		DECLARE @nombreForm VARCHAR(MAX)
		CREATE TABLE #temp (
			mostrarPais VARCHAR(MAX),
			mostrarProvincia VARCHAR(MAX),
			step2LabelProvincia VARCHAR(MAX),
			mostrarFecNac VARCHAR(MAX),
			lcfg_iid VARCHAR(MAX),
			principalServer VARCHAR(MAX),
			nombreForm VARCHAR(MAX),
			Dealer VARCHAR(MAX),
			nombreCampoDealer VARCHAR(MAX),
			solicitarCodigoActivacion int,
			codigoActivacion VARCHAR(MAX),
			groupMax VARCHAR(MAX),
			MailTo VARCHAR(MAX),
			MailSubject VARCHAR(MAX),
			MailBodyNO VARCHAR(MAX),
			MailSubjectCustomer VARCHAR(MAX),
			MailBodyCustomer VARCHAR(MAX),
			reCaptcha VARCHAR(MAX),
			condiciones VARCHAR(MAX),
			plantillaSP VARCHAR(MAX),
			automonitoreo int,
			apptype VARCHAR(MAX),
			diasPruebaCampo VARCHAR(MAX),
			diasprueba VARCHAR(MAX),
			cuentatipo VARCHAR(MAX),
			enviarEmail VARCHAR(MAX),
			emailContactoAyuda VARCHAR(MAX),
			imei VARCHAR(MAX),
			mostrarMensaje VARCHAR(MAX),
			ocultarPregunta VARCHAR(MAX),
			mailSubjectActiveAccount VARCHAR(MAX),
			mailBodyActiveAccount VARCHAR(MAX),
			emailsTemplates VARCHAR(MAX),
			nombreApp VARCHAR(MAX),
			autoActivarSP VARCHAR(MAX),
			esLandingAcotada VARCHAR(MAX),
			demo VARCHAR(MAX),
			activarPago VARCHAR(MAX),
			DealerFreemium VARCHAR(MAX),
			activarFreemium VARCHAR(MAX),
			textoInvitaPagar VARCHAR(MAX),
			tituloRegistroFreemium VARCHAR(MAX),
			textoRegistroFreemium VARCHAR(MAX),
			textoBotonFreemium VARCHAR(MAX),
			errorFreemium VARCHAR(MAX),
			errorActivacion VARCHAR(MAX),
			Public_Key VARCHAR(MAX),
			Access_Token VARCHAR(MAX),
			preapproval_plan_id_mensual VARCHAR(MAX),
			preapproval_plan_id_anual VARCHAR(MAX),
			clientId VARCHAR(MAX),
			_clientId VARCHAR(MAX),
			clientSecret VARCHAR(MAX),
			plan_id_mensual_paypal VARCHAR(MAX),
			plan_id_anual_paypal VARCHAR(MAX),
			textoConfiramaPagoFreemium VARCHAR(MAX),
			textoConfiramaPagoComun VARCHAR(MAX),
			btnVolver VARCHAR(MAX),
			lblFaltaImei VARCHAR(MAX),
			textoInicio VARCHAR(MAX),
			lblTituloForm VARCHAR(MAX),
			imeiValidated VARCHAR(MAX),
			pagoPendienteTitulo VARCHAR(MAX),
			pagoPendienteSubTitulo VARCHAR(MAX),
			pagoPendienteBajadaLinea VARCHAR(MAX),
			pagoPendienteTextoBoton VARCHAR(MAX),
			btnCancelarPago VARCHAR(MAX),
			errorValidatePending VARCHAR(50),
			lblTextoCodPromocional VARCHAR(MAX),
			planTitulo VARCHAR(MAX),
			theme VARCHAR(MAX),
			step1Placeholder VARCHAR(MAX),
			step1ShowErrorCodigoTexto1 VARCHAR(MAX),
			step1ShowErrorCodigoTexto2 VARCHAR(MAX),
			txtBtnSiguiente VARCHAR(MAX),
			txtBtnAnterior VARCHAR(MAX),
			step2BtnYaTengoCta VARCHAR(MAX),
			step2BtnSoyUsuario VARCHAR(MAX),
			step2TituloDatosPersonales VARCHAR(MAX),
			step2PlaceHolderNombre VARCHAR(MAX),
			step2ShowErrorNombre VARCHAR(MAX),
			step2PlaceHolderDireccion VARCHAR(MAX),
			step2ShowErrorDireccion VARCHAR(MAX),
			
			step3Titulo VARCHAR(MAX),
			step3PlaceHolderEmail VARCHAR(MAX),
			step3ShowErrorEmail VARCHAR(MAX),
			step3ShowLabelErrorFormatMail VARCHAR(MAX),
			step3ShowLabelErrorExisteMail VARCHAR(MAX),
			step3PlaceHolderConfirmaMail VARCHAR(MAX),
			step3ShowLabelErrorConfirmaMail VARCHAR(MAX),
			step3showLabelErrorFormatConfirmaMail VARCHAR(MAX),
			step3ShowLabelErrorCompareMail VARCHAR(MAX),
			step3showLabelErrorTel VARCHAR(MAX),
			step3PlaceHolderTel VARCHAR(MAX),
			step3showLabelErrorLongTel VARCHAR(MAX),
			step3showLabelErrorExisteTel VARCHAR(MAX),
			step3showLabelErrorConfirmaTel VARCHAR(MAX),
			step3showLabelErrorConfirmaLongTel VARCHAR(MAX),
			step3showLabelErrorCompareTel VARCHAR(MAX),
			step4TituloVerificarDatos VARCHAR(MAX),
			step4LabelNombre VARCHAR(MAX),
			step4LabelDireccion VARCHAR(MAX),
			step4LabelPais VARCHAR(MAX),
			step4LabelTelefono VARCHAR(MAX),
			step4LabelMail VARCHAR(MAX),
			step4btnVolver VARCHAR(MAX),
			step4btnEnviar VARCHAR(MAX),
			mensajeVerificaionExitosa VARCHAR(MAX),
			step3PlaceHolderConfirmaTel VARCHAR(MAX),
			step1MayorDeEdad VARCHAR(MAX),
			step2Localidad VARCHAR(MAX),
			step4FecNac VARCHAR(MAX),
			step4Provincia VARCHAR(MAX),
			steepOtrosActivar VARCHAR(MAX),
			step1CuentaYTelefono VARCHAR(MAX),
			step1CuentaYClave VARCHAR(MAX),
			step1NroCta VARCHAR(MAX),
			step1DatosErroneos VARCHAR(MAX),
			step1IngreseClave VARCHAR(MAX),
			violenciagenero VARCHAR(MAX),
			dealerViolenciagenero VARCHAR(MAX),
			campoDiscapacidad VARCHAR(MAX),
			step2ViolenciaGenero VARCHAR(MAX),
			step2Discapacidad VARCHAR(MAX),
			step2Obs VARCHAR(MAX),
			campoObs VARCHAR(MAX),
			-- WhatsApp API config
			keycontrol VARCHAR(MAX),
			beaerToken VARCHAR(MAX),
			msjvalidacion VARCHAR(MAX),
			-- WhatsApp validation fields
			validarTelefonoWhatsapp VARCHAR(MAX),
			whatsappTituloModal VARCHAR(MAX),
			whatsappSubtituloModal VARCHAR(MAX),
			whatsappPlaceholderCodigo VARCHAR(MAX),
			whatsappBtnEnviarCodigo VARCHAR(MAX),
			whatsappBtnValidar VARCHAR(MAX),
			whatsappBtnReenviar VARCHAR(MAX),
			whatsappErrorCodigoVacio VARCHAR(MAX),
			whatsappErrorCodigoInvalido VARCHAR(MAX),
			whatsappMensajeEnviado VARCHAR(MAX),
			whatsappMensajeReenviado VARCHAR(MAX),
			whatsappEnviandoCodigo VARCHAR(MAX),
			whatsappValidando VARCHAR(MAX),
			whatsappCodigoValidado VARCHAR(MAX),
			whatsappErrorEnvio VARCHAR(MAX),
			whatsappValidezCodigo VARCHAR(MAX),
			whatsappMensajeInicial VARCHAR(MAX),
			labelCustom VARCHAR(MAX),
			caracteristicaDefault VARCHAR(MAX),
			mostrarDNI VARCHAR(MAX),
			step2PlaceholderCustom VARCHAR(MAX),
			tiposDNI VARCHAR(MAX),
			defaultOptionPais VARCHAR(MAX),
			defaultOptionProvincia VARCHAR(MAX),
			paisAutocompletarDireccion VARCHAR(MAX),
			autocompletarDireccion VARCHAR(MAX));

		DECLARE cursor_json CURSOR FOR
		SELECT
		JSON_MODIFY(lcfg_ccontent, '$.lcfg_iid',
		CONVERT(VARCHAR(20),lcfg_iid)) AS lcfg_ccontent
		FROM _Datos..LandingConfig;
		OPEN cursor_json;
		FETCH NEXT FROM cursor_json INTO @json;
		WHILE @@FETCH_STATUS = 0
		BEGIN
			SELECT @nombreForm=[value] FROM OpenJson(@json)
			WHERE [key] = 'nombreForm'

			INSERT INTO #temp

			SELECT* FROM OpenJson(@json)
			WITH (
			mostrarPais VARCHAR(MAX),
			mostrarProvincia VARCHAR(MAX),
			step2LabelProvincia VARCHAR(MAX),
			mostrarFecNac VARCHAR(MAX),
			lcfg_iid VARCHAR(MAX),
			principalServer VARCHAR(MAX),
			nombreForm VARCHAR(MAX),
			Dealer VARCHAR(MAX),
			nombreCampoDealer VARCHAR(MAX),
			solicitarCodigoActivacion int,
			codigoActivacion VARCHAR(MAX),
			groupMax VARCHAR(MAX),
			MailTo VARCHAR(MAX),
			MailSubject VARCHAR(MAX),
			MailBodyNO VARCHAR(MAX),
			MailSubjectCustomer VARCHAR(MAX),
			MailBodyCustomer VARCHAR(MAX),
			reCaptcha VARCHAR(MAX),
			condiciones VARCHAR(MAX),
			plantillaSP VARCHAR(MAX),
			automonitoreo int,
			apptype VARCHAR(MAX),
			diasPruebaCampo VARCHAR(MAX),
			diasprueba VARCHAR(MAX),
			cuentatipo VARCHAR(MAX),
			enviarEmail VARCHAR(MAX),
			emailContactoAyuda VARCHAR(MAX),
			imei VARCHAR(MAX),
			mostrarMensaje VARCHAR(MAX),
			ocultarPregunta VARCHAR(MAX),
			mailSubjectActiveAccount VARCHAR(MAX),
			mailBodyActiveAccount VARCHAR(MAX),
			emailsTemplates VARCHAR(MAX),
			nombreApp VARCHAR(MAX),
			autoActivarSP VARCHAR(MAX),
			esLandingAcotada VARCHAR(MAX),
			demo VARCHAR(MAX),
			activarPago VARCHAR(MAX),
			DealerFreemium VARCHAR(MAX),
			activarFreemium VARCHAR(MAX),
			textoInvitaPagar VARCHAR(MAX),
			tituloRegistroFreemium VARCHAR(MAX),
			textoRegistroFreemium VARCHAR(MAX),
			textoBotonFreemium VARCHAR(MAX),
			errorFreemium VARCHAR(MAX),
			errorActivacion VARCHAR(MAX),
			Public_Key VARCHAR(MAX),
			Access_Token VARCHAR(MAX),
			preapproval_plan_id_mensual VARCHAR(MAX),
			preapproval_plan_id_anual VARCHAR(MAX),
			clientId VARCHAR(MAX),
			_clientId VARCHAR(MAX),
			clientSecret VARCHAR(MAX),
			plan_id_mensual_paypal VARCHAR(MAX),
			plan_id_anual_paypal VARCHAR(MAX),
			textoConfiramaPagoFreemium VARCHAR(MAX),
			textoConfiramaPagoComun VARCHAR(MAX),
			btnVolver VARCHAR(MAX),
			lblFaltaImei VARCHAR(MAX),
			textoInicio VARCHAR(MAX),
			lblTituloForm VARCHAR(MAX),
			imeiValidated VARCHAR(MAX),
			pagoPendienteTitulo VARCHAR(MAX),
			pagoPendienteSubTitulo VARCHAR(MAX),
			pagoPendienteBajadaLinea VARCHAR(MAX),
			pagoPendienteTextoBoton VARCHAR(MAX),
			btnCancelarPago VARCHAR(MAX),
			errorValidatePending VARCHAR(50),
			lblTextoCodPromocional VARCHAR(MAX),
			planTitulo VARCHAR(MAX),
			theme VARCHAR(MAX),
			step1Placeholder VARCHAR(MAX),
			step1ShowErrorCodigoTexto1 VARCHAR(MAX),
			step1ShowErrorCodigoTexto2 VARCHAR(MAX),
			txtBtnSiguiente VARCHAR(MAX),
			txtBtnAnterior VARCHAR(MAX),
			step2BtnYaTengoCta VARCHAR(MAX),
			step2BtnSoyUsuario VARCHAR(MAX),
			step2TituloDatosPersonales VARCHAR(MAX),
			step2PlaceHolderNombre VARCHAR(MAX),
			step2ShowErrorNombre VARCHAR(MAX),
			step2PlaceHolderDireccion VARCHAR(MAX),

			labelCustom VARCHAR(MAX),
			mostrarDNI VARCHAR(MAX),
			step2PlaceholderCustom VARCHAR(MAX),
			tiposDNI VARCHAR(MAX),
			defaultOptionPais VARCHAR(MAX),
			defaultOptionProvincia VARCHAR(MAX),

			step2ShowErrorDireccion VARCHAR(MAX),
			step3Titulo VARCHAR(MAX),
			step3PlaceHolderEmail VARCHAR(MAX),
			step3ShowErrorEmail VARCHAR(MAX),
			step3ShowLabelErrorFormatMail VARCHAR(MAX),
			step3ShowLabelErrorExisteMail VARCHAR(MAX),
			step3PlaceHolderConfirmaMail VARCHAR(MAX),
			step3ShowLabelErrorConfirmaMail VARCHAR(MAX),
			step3showLabelErrorFormatConfirmaMail VARCHAR(MAX),
			step3ShowLabelErrorCompareMail VARCHAR(MAX),
			step3showLabelErrorTel VARCHAR(MAX),
			step3PlaceHolderTel VARCHAR(MAX),
			step3showLabelErrorLongTel VARCHAR(MAX),
			step3showLabelErrorExisteTel VARCHAR(MAX),
			step3showLabelErrorConfirmaTel VARCHAR(MAX),
			step3showLabelErrorConfirmaLongTel VARCHAR(MAX),
			step3showLabelErrorCompareTel VARCHAR(MAX),
			step4TituloVerificarDatos VARCHAR(MAX),
			step4LabelNombre VARCHAR(MAX),
			step4LabelDireccion VARCHAR(MAX),
			step4LabelPais VARCHAR(MAX),
			step4LabelTelefono VARCHAR(MAX),
			step4LabelMail VARCHAR(MAX),
			step4btnVolver VARCHAR(MAX),
			step4btnEnviar VARCHAR(MAX),
			mensajeVerificaionExitosa VARCHAR(MAX),
			step3PlaceHolderConfirmaTel VARCHAR(MAX),
			step1MayorDeEdad VARCHAR(MAX),
			step2Localidad VARCHAR(MAX),
			step4FecNac VARCHAR(MAX),
			step4Provincia VARCHAR(MAX),
			steepOtrosActivar VARCHAR(MAX),
			step1CuentaYTelefono VARCHAR(MAX),
			step1CuentaYClave VARCHAR(MAX),
			step1NroCta VARCHAR(MAX),
			step1DatosErroneos VARCHAR(MAX),
			step1IngreseClave VARCHAR(MAX),
			violenciagenero VARCHAR(MAX),
			dealerViolenciagenero VARCHAR(MAX),
			campoDiscapacidad VARCHAR(MAX),
			step2ViolenciaGenero VARCHAR(MAX),
			step2Discapacidad VARCHAR(MAX),
			step2Obs VARCHAR(MAX),
			campoObs VARCHAR(MAX),





			-- WhatsApp API config
			keycontrol VARCHAR(MAX),
			beaerToken VARCHAR(MAX),
			msjvalidacion VARCHAR(MAX),
			-- WhatsApp validation fields
			validarTelefonoWhatsapp VARCHAR(MAX),
			whatsappTituloModal VARCHAR(MAX),
			whatsappSubtituloModal VARCHAR(MAX),
			whatsappPlaceholderCodigo VARCHAR(MAX),
			whatsappBtnEnviarCodigo VARCHAR(MAX),
			whatsappBtnValidar VARCHAR(MAX),
			whatsappBtnReenviar VARCHAR(MAX),
			whatsappErrorCodigoVacio VARCHAR(MAX),
			whatsappErrorCodigoInvalido VARCHAR(MAX),
			whatsappMensajeEnviado VARCHAR(MAX),
			whatsappMensajeReenviado VARCHAR(MAX),
			whatsappEnviandoCodigo VARCHAR(MAX),
			whatsappValidando VARCHAR(MAX),
			whatsappCodigoValidado VARCHAR(MAX),
			whatsappErrorEnvio VARCHAR(MAX),
			whatsappValidezCodigo VARCHAR(MAX),
			whatsappMensajeInicial VARCHAR(MAX),
			paisAutocompletarDireccion VARCHAR(MAX),
			caracteristicaDefault VARCHAR(MAX),
			autocompletarDireccion VARCHAR(MAX));

				UPDATE #temp
				SET codigoActivacion=(SELECT [value] FROM OpenJson(@json)
									  WHERE [key] = 'codigoActivacion')
				WHERE @nombreForm = @nombreForm
			FETCH NEXT FROM cursor_json INTO @json;
		END;
		CLOSE cursor_json;
		DEALLOCATE cursor_json;
		SELECT * FROM #temp;
		DROP TABLE #temp;

	END
	ELSE
	BEGIN
		SELECT lcfg_iid, lcfg_cname, JSON_MODIFY(lcfg_ccontent, '$.lcfg_iid',
		CONVERT(VARCHAR(20),lcfg_iid)) AS lcfg_ccontent
		FROM _Datos..LandingConfig A
		WHERE lcfg_iid=@nombre
	END
END