
var _uiApplicationName = "SmartTrack";
Ext.application({
    extend: "Common.Application",
    name: "SmartTrack",
    controllers: [
        "AutomonitoreoFormController",
        "AwccUsuariosByCuentaGridController",
        "BitacoraController",
        "CheckPointSelecterHelperController",
        "CheckPointsFormController",
        "CheckPointsGridController",
        "CheckPointsHelperController",
        "CuentaController",
        "CuentaFormController",
        "CuentaGridController",
        "CuentaHelperChekController",
        "CuentaHelperControllerBAK",
        "CuentaRecepcionController",
        "CuentaReporteController",
        "DealerHelperController",
        "EstadoItemController",
        "EventImagesController",
        "EventObservacionesController",
        "EventObservacionesFormController",
        "EventoController",
        "EventoFormController",
        "EventoMapController",
        "EventoReCategorizacionFormController",
        "EventosImagesController",
        "EventosMapController",
        "EventoSonidoController",
        "EventosTrGridController",
        "EventoTimeLineController",
        "EventoTimeLineFullController",
        "EventPhoneController",
        "EventProcesamientoController",
        "EventRepAutController",
        "EventSelecterHelperController",
        "EventSmsController",
        "ImagenesController",
        "ImagePanelController",
        "LlamadaContactarGridController",
        "LlamadaGridController",
        "LlamadaHelperController",
        "LlamadaRealizadasGridController",
        "LlamadasJuridiccionalesGridController",
        "LlamadasReaFullGridController",
        "LlamadasSmartpanicsGridController",
        "m_cuenta_videoPanelController",
        "m_cuentas_video_linksFormController",
        "m_cuentas_video_linksGridController",
        "m_cuentas_videoFormController",
        "m_cuentas_videoGridController",
        "MailFormController",
        "ModuleController",
        "MulticuentaServicioTecnicoGridController",
        "MultimediaEventosPanelController",
        "MultimediaGridController",
        "NotificacionesGridController",
        "PasswordFormController",
        "PPushQueueGridController",
        "RestriccionesFormController",
        "RestriccionesGridController",
        "RoutesAgendaFormController",
        "RoutesController",
        "RoutesFormController",
        "RoutesGridController",
        "RoutesPointsFormController",
        "RoutesPointsGridController",
        "RoutesPointsMapController",
        "RoutesProgramFormController",
        "RoutesProgramFormWizarController",
        "RoutesProgramGridController",
        "SelecterHelperController",
        "SmartMailController",
        "SmartMailFormController",
        "SmartMailProgramGridController",
        "SmartpanicsHelperController",
        "SmartTrackConfigController",
        "SmartTrackController",
        "SmarttrackCuentaController",
        "SmartTrackFormHelperController",
        "SmartTrackGridController",
        "SmartTrackMonitoreoController",
        "SmartTrackPendingGridController",
        "SmartTrackPushNotificationsGridController",
        "SmsConmutadosGridController",
        "SmsGridController",
        "SmsRecibidosGridController",
        "SoftguardContactoFormController",
        "SoftguardContactoGridController",
        "SoftguardCuentaCopyController",
        "SoftguardCuentaNewController",
        "SoftguardEstadoController",
        "SoftguardNotaController",
        "SoftguardSmsController",
        "SoftguardSmsFormController",
        "SoftguardTestController",
        "SoftguardUsuarioFormController",
        "SoftguardUsuarioGridController",
        "SPDispSeguimientoMapController",
        "SPReadOnlyController",
        "SPSeguientoGridController",
        "TablasTelefonosJurisdiccionalesAccGridController",
        "UsuariosSelecterHelperController",
        "VCAllSeguimientoMapController",
        "VCReadOnlyController",
        "VCSeguimientoGridController",
        "VCSeguimientoInfoObjetivoController",
        "VCSeguimientoMapController",
        "VCSeguimientoPosicionesGridController",
        "VCSeguimientoRutaGridController",
        "VigiControllGpsFullController",
        "VigiControlMonitoreoController",
    ],
    quickTips: false,
    platformConfig: {
        desktop: {
            quickTips: true,
        },
    },

    requires: [
        "SmartTrack.*",
        "Ext.Responsive",
        "Common.*",
        "Ext.chart.*"
    ],

    launch: function () {
        console.log(arguments);
    },
    mainView: "SmartTrack.view.MetadataViewport",

    onAppUpdate: function () {
        Ext.Msg.confirm("Actualizacion detectada", "Reload?", function (choice) {
            if (choice === "yes") {
                window.location.reload();
            }
        });
    },
});
