Ext.define('SmartPanics.model.HtmlUserModuleSearchModel', {
    extend: 'Ext.data.Model',
    idProperty: 'Id',
    fields: [ 
        {name:'Account', type: 'string'},
        {name:'Address', type: 'string'},
        {name:'AddressLat', type: 'string'},
        {name:'AddressLong', type: 'string'},
        {name:'Body', type: 'string'},
        {name:'City', type: 'string'},
        {name:'Country', type: 'string'},
        {name:'Email', type: 'string'},
        {name:'EmployeeCount', type: 'string'},
        {name:'Facebook', type: 'string'},
        {name:'Fax', type: 'string'},
        {name:'Google', type: 'string'},
        {name:'Id', type: 'string'},
        {name:'LargeComment', type: 'string'},
        {name:'LegalName', type: 'string'},
        {name:'Linkedin', type: 'string'},
        {name:'Location', type: 'string'},
        {name:'Mobile', type: 'string'},
        {name:'Name', type: 'string'},
        {name:'NationalTax', type: 'string'},
        {name:'OrganizationType', type: 'string'},
        {name:'Phone', type: 'string'},
        {name:'RowNumber', type: 'string'},
        {name:'SmallComment', type: 'string'},
        {name:'State', type: 'string'},
        {name:'StateTax', type: 'string'},
        {name:'Status', type: 'string'},
        {name:'Turnover', type: 'string'},
        {name:'Twitter', type: 'string'},
        {name:'Web', type: 'string'},
        {name:'Zip', type: 'string'},
        {name:'udm_disponible', type: 'string'},
        {name:'udm_idKey', type: 'string'},
        {name:'udm_key_reference', type: 'string'},
        {name:'udm_modulo', type: 'string'},
        {name:'udw_apellido', type: 'string'},
        {name:'udw_clave', type: 'string'},
        {name:'udw_empresa', type: 'string'},
        {name:'udw_estado', type: 'string'},
        {name:'udw_idKey', type: 'string'},
        {name:'udw_metadata', type: 'string'},
        {name:'udw_nombre', type: 'string'},
        {name:'udw_usuario', type: 'string'},
        {name:'ums_data', type: 'string'},
        {name:'ums_idModules', type: 'string'}
    ],
    proxy : {
		type : 'rest',
		url : '/Rest/Search/HtmlUserModule',
		appendId : false,
        reader: {
            type : 'json',
            rootProperty : 'rows',
            totalProperty : 'total'
        }
	}
});