-- ============================================================
-- Job: DefragDB
-- Generado por pull-db.ps1 - NO editar manualmente
-- ============================================================
USE msdb;
GO

IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N'DefragDB')
    EXEC msdb.dbo.sp_delete_job @job_name = N'DefragDB', @delete_unused_schedule = 0;
GO

EXEC msdb.dbo.sp_add_job
    @job_name          = N'DefragDB',
    @enabled           = 1,
    @description       = N'No description available.',
    @category_name     = N'Database Maintenance',
    @owner_login_name  = N'sa',
    @delete_level      = 0;
GO

EXEC msdb.dbo.sp_add_jobserver
    @job_name   = N'DefragDB',
    @server_name = N'(LOCAL)';
GO

EXEC msdb.dbo.sp_add_jobstep
    @job_name          = N'DefragDB',
    @step_id           = 1,
    @step_name         = N'DefragTablas',
    @subsystem         = N'TSQL',
    @command           = N'Execute _Datos.dbo.DBA_IndexDefrag
          @executeSQL           = 1		-- 1 = execute the SQL generated by this proc; 0 = print command only
        , @minFragmentation     = 80
        , @printCommands        = 0		-- 1 = print commands to screen; 0 = do not print commands
        , @debugMode            = 0		-- 1 = display debug comments; helps with troubleshooting; 0 = do not display debug comments	
        , @printFragmentation   = 0		-- 1 = print fragmentation to screen; 0 = do not print fragmentation
        , @database             = ''_Tablas''
',
    @database_name     = N'_Tablas',
    @on_success_action = 3,
    @on_success_step_id = 0,
    @on_fail_action    = 2,
    @on_fail_step_id   = 0,
    @retry_attempts    = 0,
    @retry_interval    = 1;
GO

EXEC msdb.dbo.sp_add_jobstep
    @job_name          = N'DefragDB',
    @step_id           = 2,
    @step_name         = N'DefragSistema',
    @subsystem         = N'TSQL',
    @command           = N'Execute _Datos.dbo.DBA_IndexDefrag
          @executeSQL           = 1		-- 1 = execute the SQL generated by this proc; 0 = print command only
        , @minFragmentation     = 80
        , @printCommands        = 0		-- 1 = print commands to screen; 0 = do not print commands
        , @debugMode            = 0		-- 1 = display debug comments; helps with troubleshooting; 0 = do not display debug comments	
        , @printFragmentation   = 0		-- 1 = print fragmentation to screen; 0 = do not print fragmentation
        , @database             = ''_Sistema''',
    @database_name     = N'_Sistema',
    @on_success_action = 3,
    @on_success_step_id = 0,
    @on_fail_action    = 2,
    @on_fail_step_id   = 0,
    @retry_attempts    = 0,
    @retry_interval    = 1;
GO

EXEC msdb.dbo.sp_add_jobstep
    @job_name          = N'DefragDB',
    @step_id           = 3,
    @step_name         = N'DefragDatos',
    @subsystem         = N'TSQL',
    @command           = N'Execute _Datos.dbo.DBA_IndexDefrag
          @executeSQL           = 1		-- 1 = execute the SQL generated by this proc; 0 = print command only
        , @minFragmentation     = 80
        , @printCommands        = 0		-- 1 = print commands to screen; 0 = do not print commands
        , @debugMode            = 0		-- 1 = display debug comments; helps with troubleshooting; 0 = do not display debug comments	
        , @printFragmentation   = 0		-- 1 = print fragmentation to screen; 0 = do not print fragmentation
        , @database             = ''_Datos''',
    @database_name     = N'_Datos',
    @on_success_action = 3,
    @on_success_step_id = 0,
    @on_fail_action    = 2,
    @on_fail_step_id   = 0,
    @retry_attempts    = 0,
    @retry_interval    = 1;
GO

EXEC msdb.dbo.sp_add_jobstep
    @job_name          = N'DefragDB',
    @step_id           = 4,
    @step_name         = N'TaskStatus',
    @subsystem         = N'TSQL',
    @command           = N'-- Aviso que la tarea esta funcionando	60min * 24hs *8dias = 11520
Exec [dbo].[TaskStatus_SetLastExecutedTime] @JobName = N''DefragDB'', @Repetition = 11520
--	',
    @database_name     = N'_Datos',
    @on_success_action = 1,
    @on_success_step_id = 0,
    @on_fail_action    = 2,
    @on_fail_step_id   = 0,
    @retry_attempts    = 0,
    @retry_interval    = 0;
GO

EXEC msdb.dbo.sp_update_job
    @job_name      = N'DefragDB',
    @start_step_id = 1;
GO

EXEC msdb.dbo.sp_add_schedule
    @schedule_name          = N'DefragDB',
    @enabled                = 1,
    @freq_type              = 8,
    @freq_interval          = 64,
    @freq_subday_type       = 1,
    @freq_subday_interval   = 0,
    @freq_relative_interval = 0,
    @freq_recurrence_factor = 1,
    @active_start_date      = 20160101,
    @active_end_date        = 99991231,
    @active_start_time      = 43000,
    @active_end_time        = 235959;
GO

EXEC msdb.dbo.sp_attach_schedule
    @job_name      = N'DefragDB',
    @schedule_name = N'DefragDB';
GO
