
var _uiApplicationName = "Awcc";
Ext.application({
    extend: "Common.Application",
    name: "Awcc",
    controllers: [
"AwccController",
"VigiControlMonitoreoController",
"VigiControllGpsFullController",
"VehicleHistoricoController",
"VCReadOnlyController",
"TelefonoPlantillaController",
"TablasTelefonosJurisdiccionalesAccGridController",
"TablasTelefonosJuridiccionaesAccHelperController",
"SPSeguientoGridController",
"SPReadOnlyController",
"SPEventoVideoController",
"SPDispSeguimientoMapController",
"SoftguardZonaFormController",
"SoftguardZonaController",
"SoftguardUsuarioGridController",
"SoftguardUsuarioFormController",
"SoftguardTestController",
"SoftguardSmsFormController",
"SoftguardSmsController",
"SoftguardPanelGridController",
"SoftguardPanelController",
"SoftguardNotaController",
"SoftguardMedicoFormController",
"SoftguardHorarioFormController",
"SoftguardFalsaController",
"SoftguardEstadoController",
"SoftguardCuentaNewController",
"SoftguardCuentaCopyController",
"SoftguardContactoGridController",
"SoftguardContactoFormController",
"SmsRecibidosGridController",
"SmsGridController",
"SmsEnvioFormController",
"SmsConmutadosGridController",
"SmsAWCCGridController",
"SMPAttachGridController",
"SmartTrackGridController",
"SmartPanicsMonitoreoController",
"SmartpanicsHelperController",
"SmartPanicsGeocercasGridController",
"SmartPanicGridController",
"SmartPanicFormHelperController",
"SmartMailProgramGridController",
"SmartMailFormController",
"SmartMailController",
"ServTecVisitasGridController",
"ServTecVisitasFormController",
"ServTecTecnicoVisitasGridController",
"ServTecReclamosGridController",
"ServTecProductosOrdenGridController",
"ServTecPanelController",
"ServTecObservacionesGridController",
"ServTecMovilVisitasGridController",
"ServTecMapFormController",
"ServTecHistoricoGridController",
"ServTecGridController",
"ServTecFullFormController",
"SerTecROController",
"SelecterHelperController",
"ScheduleGridController",
"ScheduleFormController",
"ReporteMulticuentaController",
"ReporteGraficoController",
"ReporteEventosController",
"ProductGridController",
"PasswordFormController",
"ParticionFormEditController",
"ParticionFormController",
"ParticionesGridController",
"ParticionesCopyFormController",
"ParticionesChooserController",
"SoftguardUsuarioGrid2Controller",
"p_objetos_modificacionesGridController",
"OrdenServTecController",
"NotificacionesPanelController",
"NotificacionesGridController",
"MulticuentaZonasGridController",
"MulticuentaZonaCuentaFormController",
"MulticuentaServicioTecnicoGridController",
"ModuleController",
"MGOrganizationController",
"MGCuentaController",
"MGComprobantesGridController",
"MGClientHelperController",
"MGClientFormController",
"MedicoGridController",
"MapguardMovilController",
"MapGuardGridController",
"MapGuardGpsController",
"MailFormController",
"m_cuentas_videoGridController",
"m_cuentas_videoFormController",
"m_cuentas_video_linksGridController",
"m_cuentas_video_linksFormController",
"m_cuenta_videoPanelController",
"LlamadaTelefonosDealerGridController",
"LlamadasSmartpanicsGridController",
"LlamadasReaFullGridController",
"LlamadasJuridiccionalesGridController",
"LlamadaRealizadasGridController",
"LlamadaHelperController",
"LlamadaGridController",
"LlamadaContactarGridController",
"ImagePanelController",
"ImagenesController",
"HorarioToleranciaController",
"HorarioExcepcionController",
"HorarioController",
"HorarioAlternativoController",
"GeocercaGridController",
"EventSmsController",
"EventSelecterHelperController",
"EventRepAutController",
"EventProcesamientoController",
"EventPhoneController",
"EventoTimeLineFullController",
"EventosTrGridController",
"EventoSonidoController",
"EventoReCategorizacionFormController",
"EventoMapController",
"EventoFormController",
"EventoController",
"EventObservacionesFormController",
"EventObservacionesController",
"EventImagesController",
"EstadoPruebaFormController",
"EstadoItemController",
"DocumentosFileGridController",
"CuentaROController",
"CuentaReporteController",
"CuentaRecepcionController",
"CuentaHelperControllerBAK",
"CuentaGridController",
"CuentaFormController",
"CuentaEventosPendientesController",
"CuentaController",
"BitacoraController",
"AwccUsuariosByCuentaGridController",
"AwccUsuariosByCuentaFormController",
"AwccUsuarioFromController",
"AwccMailFormController",
"AutomonitoreoFormController",

    ],
    quickTips: false,
    platformConfig:{
        desktop:{
            quickTips: true,
        },
    },

    requires: [
        "Awcc.*",
        "Ext.Responsive",
        "Common.*",
    ],

    launch: function() {
        console.log(arguments);
    },
    mainView: "Awcc.view.MetadataViewport",

    onAppUpdate: function() {
        Ext.Msg.confirm("Actualizacion detectada", "Reload?", function(choice) {
            if (choice === "yes")
            {
                window.location.reload();
            }
        });
    },
});