Ext.define('WeSafe.model.ConfuguraLandingSearchModel', {
    extend: 'Ext.data.Model',
    idProperty: 'nombreForm',
    fields: [{
        name: 'principalServer',
        type: 'string'
    },
    { name: 'nombreForm', type: 'string' },
    { name: 'Dealer', type: 'string' },
    { name: 'nombreCampoDealer', type: 'string' },
    { name: 'solicitarCodigoActivacion', type: 'string' },
    { name: 'codigoActivacion', type: 'string' },
    { name: 'groupMax', type: 'int' },
    { name: 'MailTo', type: 'string' },
    { name: 'MailSubject', type: 'string' },
    { name: 'MailBodyNO', type: 'string' },
    { name: 'MailSubjectCustomer', type: 'string' },
    { name: 'MailBodyCustomer', type: 'string' },
    { name: 'reCaptcha', type: 'string' },
    { name: 'condiciones', type: 'string' },
    { name: 'plantillaSP', type: 'string' },
    { name: 'automonitoreo', type: 'string' },
    { name: 'diasPruebaCampo', type: 'string' },
    { name: 'diasprueba', type: 'int' },
    { name: 'cuentatipo', type: 'string' },
    { name: 'enviarEmail', type: 'string' },
    { name: 'emailContactoAyuda', type: 'string' },
    { name: 'imei', type: 'string' },
    { name: 'mostrarMensaje', type: 'string' },
    { name: 'ocultarPregunta', type: 'string' },
    { name: 'mailSubjectActiveAccount', type: 'string' },
    { name: 'mailBodyActiveAccount', type: 'string' },
    { name: 'emailsTemplates', type: 'string' },
    { name: 'nombreApp', type: 'string' },
    { name: 'autoActivarSP', type: 'string' },
    { name: 'esLandingAcotada', type: 'string' },
    { name: 'demo', type: 'string' },
    { name: 'activarPago', type: 'string' },
    { name: 'DealerFreemium', type: 'string' },
    { name: 'activarFreemium', type: 'string' },
    { name: 'textoInvitaPagar', type: 'string' },
    { name: 'tituloRegistroFreemium', type: 'string' },
    { name: 'textoRegistroFreemium', type: 'string' },
    { name: 'textoBotonFreemium', type: 'string' },
    { name: 'errorFreemium', type: 'string' },
    { name: 'errorActivacion', type: 'string' },
    { name: 'Public_Key', type: 'string' },
    { name: 'Access_Token', type: 'string' },
    { name: 'preapproval_plan_id_mensual', type: 'string' },
    { name: 'preapproval_plan_id_anual', type: 'string' },
    { name: 'clientId', type: 'string' },
    { name: '_clientId', type: 'string' },
    { name: 'clientSecret', type: 'string' },
    { name: 'plan_id_mensual_paypal', type: 'string' },
    { name: 'plan_id_anual_paypal', type: 'string' },
    { name: 'textoConfiramaPagoFreemium', type: 'string' },
    { name: 'textoConfiramaPagoComun', type: 'string' },
    { name: 'btnVolver', type: 'string' },
    { name: 'lblFaltaImei', type: 'string' },
    { name: 'textoInicio', type: 'string' },
    { name: 'lblTituloForm', type: 'string' },
    { name: 'imeiValidated', type: 'string' },
    { name: 'pagoPendienteTitulo', type: 'string' },
    { name: 'pagoPendienteSubTitulo', type: 'string' },
    { name: 'pagoPendienteBajadaLinea', type: 'string' },
    { name: 'pagoPendienteTextoBoton', type: 'string' },
    { name: 'btnCancelarPago', type: 'string' },
    { name: 'errorValidatePending', type: 'string' },
    { name: 'lblTextoCodPromocional', type: 'string' },
    { name: 'planTitulo', type: 'string' },
    { name: 'theme', type: 'string' },
    { name: 'step1Placeholder', type: 'string' },
    { name: 'step1ShowErrorCodigoTexto1', type: 'string' },
    { name: 'step1ShowErrorCodigoTexto2', type: 'string' },
    { name: 'txtBtnSiguiente', type: 'string' },
    { name: 'txtBtnAnterior', type: 'string' },
    { name: 'step2BtnYaTengoCta', type: 'string' },
    { name: 'step2BtnSoyUsuario', type: 'string' },
    { name: 'step2TituloDatosPersonales', type: 'string' },
    { name: 'step2PlaceHolderNombre', type: 'string' },
    { name: 'step2ShowErrorNombre', type: 'string' },
    { name: 'step2PlaceHolderDireccion', type: 'string' },
    { name: 'step2ShowErrorDireccion', type: 'string' },
    { name: 'step3Titulo', type: 'string' },
    { name: 'step3PlaceHolderEmail', type: 'string' },
    { name: 'step3ShowErrorEmail', type: 'string' },
    { name: 'step3ShowLabelErrorFormatMail', type: 'string' },
    { name: 'step3ShowLabelErrorExisteMail', type: 'string' },
    { name: 'step3PlaceHolderConfirmaMail', type: 'string' },
    { name: 'step3ShowLabelErrorConfirmaMail', type: 'string' },
    { name: 'step3showLabelErrorFormatConfirmaMail', type: 'string' },
    { name: 'step3ShowLabelErrorCompareMail', type: 'string' },
    { name: 'step3PlaceHolderTel', type: 'string' },
    { name: 'step3PlaceHolderConfirmaTel', type: 'string' },
    { name: 'step3showLabelErrorTel', type: 'string' },
    { name: 'step3showLabelErrorLongTel', type: 'string' },
    { name: 'step3showLabelErrorExisteTel', type: 'string' },
    { name: 'step3showLabelErrorConfirmaTel', type: 'string' },
    { name: 'step3showLabelErrorConfirmaLongTel', type: 'string' },
    { name: 'step3showLabelErrorCompareTel', type: 'string' },
    { name: 'step4TituloVerificarDatos', type: 'string' },
    { name: 'step4LabelNombre', type: 'string' },
    { name: 'step4LabelDireccion', type: 'string' },
    { name: 'step4LabelPais', type: 'string' },
    { name: 'step4LabelTelefono', type: 'string' },
    { name: 'step4LabelMail', type: 'string' },
    { name: 'step4btnVolver', type: 'string' },
    { name: 'step4btnEnviar', type: 'string' },
    { name: 'mensajeVerificaionExitosa', type: 'string' },
    { name: 'step1MayorDeEdad', type: 'string' },
    { name: 'step2Localidad', type: 'string' },
    { name: 'step4FecNac', type: 'string' },
    { name: 'step4Provincia', type: 'string' },
    { name: 'steepOtrosActivar', type: 'string' },
    { name: 'step1CuentaYTelefono', type: 'string' },
    { name: 'step1CuentaYClave', type: 'string' },
    { name: 'step1NroCta', type: 'string' },
    { name: 'step1DatosErroneos', type: 'string' },
    { name: 'step1IngreseClave', type: 'string' }
    ],
    idProperty: 'nombreForm',
    proxy: {
        type: 'rest',

        reader: {
            type: 'json',
            rootProperty: 'rows',
            totalProperty: 'total'
        },
        url: '/rest/search/SearchLandingConfig',
        appendId: false
    }
});