//MIGRADO2024
Ext.define("Common.view.CuentaPanelFormView", {
  extend: "Ext.form.Panel",
  alias: "widget.panelformview",
  margin: 0,
  layout: {
    type: "vbox",
    align: "stretch",
  },
  dockedItems: [
    {
      xtype: "toolbar",
      items: [
        {
          text: "Guardar",
          iconCls: "save",
          action: "save",
        },
        {
          text: "Cambio estado",
          itemId: "cambioEstado",
          iconCls: "icon-arrow-switch",
        },
      ],
      // cierro items
    },
  ], // cierro dockeditems
  items: [
    {
      xtype: "combo",
      fieldLabel: "Mostrar foto",
      store: "SiNoStore",
      displayField: "Name",
      queryMode: "local",
      forceSelection: true,
      editable: false,
      valueField: "Value",
      name: "pan_nmostrar",
      hidden: true,
      anchor: "20%",
      minWidth: 100,
      itemId: "mostrarfotopanel",
    },
    {
      xtype: "container",
      layout: "hbox",
      margin: "0 0 5 0",
      items: [
        {
          xtype: "combo",
          store: "SoftguardTablaPanelesStore",
          fieldLabel: "Panel",
          itemId: "paneles",
          displayField: "_pan_cdescripcion",
          valueField: "pan_ccodigo",
          name: "pan_ccodigo",
          flex: 1,
          allowBlank: false,
          //multiselect: false,
          editable: true,
          typeAhead: true,
          queryMode: "local",
          forceSelection: true,
          lastQuery: "",
        },
        {
          xtype: "button",
          text: "Ver",
          action: "btnManual",
        },
        {
          xtype: "button",
          text: "Configurar",
          action: "Configurar",
          itemId: "configurar",
          hidden: true,
        },
      ],
    },
    {
      xtype: "container",
      anchor: "100%",
      layout: "hbox",
      margin: "0 0 5 0",
      items: [
        {
          xtype: "combo",
          fieldLabel: "Comandos",
          itemId: "pan_ireceptor",
          name: "pan_ireceptor",
          displayField: "rec_cdescripcion",
          valueField: "rec_iid",
          allowBlank: true,
          queryMode: "local",
          flex: 1,
          forceSelection: true,
          lastQuery: "",
        },
        {
          xtype: "combo",
          fieldLabel: "Modelo",
          labelAlign: "left",
          editable: false,
          itemId: "pan_rpmidkey",
          name: "pan_rpmidkey",
          displayField: "_marcamodelo",
          valueField: "rpm_idKey",
          allowBlank: true,
          queryMode: "local",
          flex: 1,
          forceSelection: true,
          //plugins: ["clearbutton"],
        },
      ],
    }, 
    {
      xtype: "combo",
      fieldLabel: "Modem envío comandos SMS",
      itemId: "pan_cModemSMS",
      name: "pan_cModemSMS",
      displayField: "sms_cdescripcion",
      valueField: "sms_icodigo",
      allowBlank: true,
      queryMode: "local",
      //flex: 1,
      forceSelection: false,
    },
    {
      xtype: "textarea",
      anchor: "100%",
      name: "pan_mubicacion",
      fieldLabel: "Ubicación",
    },
    {
      xtype: "textfield",
      fieldLabel: "Clave",
      name: "pan_cClavePanel",
    } /* {
    				xtype : 'combo',
					store : [[1,'Sí'],[2,'No']],
					displayField: 'Name',
					valueField: 'Value',
                    readOnly: false,
					fieldLabel : 'mostrar',
					name : 'pan_nmostrar'
				}, */,
    {
      xtype: "container",
      anchor: "100%",
      layout: "hbox",
      itemId: "callerContainer",
      items: [
        {
          xtype: "container",
          flex: 1,
          items: [
            {
              xtype: "textfield",
              fieldLabel: "Caller Id 1",
              name: "pan_ccallerid1",
            },
            {
              xtype: "textfield",
              fieldLabel: "Caller Id 2",
              name: "pan_ccallerid2",
            },
            {
              xtype: "textfield",
              fieldLabel: "Caller Id 3",
              name: "pan_ccallerid3",
            },
          ],
        },
        {
          xtype: "container",
          flex: 1,
          items: [
            {
              xtype: "textfield",
              fieldLabel: "Caller Id 4",
              name: "pan_ccallerid4",
            },
            {
              xtype: "textfield",
              fieldLabel: "Caller Id 5",
              name: "pan_ccallerid5",
            },
            {
              xtype: "textfield",
              fieldLabel: "Sender Sms",
              name: "pan_csender",
            },
          ],
        },
      ],
    },
    {
      xtype: "fieldset",
      anchor: "100%",
      title: "Conexión celular",
      itemId: "conexionFieldset",
      layout: "vbox",
      items: [
        {
          xtype: "container",
          layout: "hbox",
          width: "100%",
          margin: "0 0 5 0",
          items: [
            {
              xtype: "combo",
              store: "SoftguardTablaPanelesStore",
              itemId: "equipos",
              displayField: "pan_cdescripcion",
              valueField: "pan_ccodigo",
              fieldLabel: "Equipo",
              name: "pan_cgprs",
              queryMode: "local",
              flex: 1,
            },
            {
              xtype: "button",
              text: "Ver",
              action: "btnManual2",
            },
          ],
        },
        {
          xtype: "container",
          layout: "hbox",
          width: "100%",
          items: [
            {
              xtype: "textfield",
              fieldLabel: " Número de teléfono SIM1",
              name: "pan_cnrosim1",
              flex: 1,
              labelWidth: 250,
              margin: "0 10 0 0",
            },
            {
              xtype: "textfield",
              fieldLabel: " Empresa",
              name: "pan_ccompania1",
              flex: 1,
            },
          ],
        },
        {
          xtype: "container",
          layout: "hbox",
          width: "100%",
          margin: "5 0 0 0",
          items: [
            {
              xtype: "textfield",
              fieldLabel: " Número de teléfono SIM2",
              name: "pan_cnrosim2",
              flex: 1,
              labelWidth: 250,
              margin: "0 10 0 0",
            },
            {
              xtype: "textfield",
              fieldLabel: " Empresa",
              name: "pan_ccompania2",
              flex: 1,
            },
          ],
        },
      ],
    },
  ],
});
