const GREEN = '#4CAF50';
const ORANGE = '#ff6600';
const RED = '#f44336';
const GREY = '#9E9E9E';
const BLUE = '#2196F3';
const BACKGROUND_GREEN = 'wrg-tree-node-green';
const BACKGROUND_RED = 'wrg-tree-node-red';
const BACKGROUND_ORANGE = 'wg-tree-node-orange';
const BACKGROUND_GREY = 'wrg-tree-node-grey';
const BACKGROUND_BLUE = 'wrg-tree-node-blue';


var _uiApplicationName = "WebRemoto";
Ext.application({
    extend: "Common.Application",
    name: "WebRemoto",
    controllers: [
"AsignacionMovilCuentaGridController",
"AtencionEventoController",
"AtencionEventoGuiadoController",
"DocumentosGridController",
"EventosPTGridController",
"GrabarLllamadaEntranteController",
"m_llavesROFormController",
"NotaROController",
"NotaTemporalROController",
"PanelDescripcionByEventoController",
"PosponerCierreController",
"ProcesarTodoFullFormController",
"SerTecFormController",
"ServTecMRWFormController",
"SMSMasivoFormController",
"SoftguardVehiculosGridController",
"SpChatFormController",
"WebRemotoController",
"WebRemotoNorthController",
"WhatsappEnvioFormController",
"ZonaImagenByEventoController",
"VigiControlMonitoreoController",
"VigiControllGpsFullController",
"VideoPreviewController",
"VideoController",
"VictimariosFormController",
"VictimariosController",
"VehicleSlaveGpsController",
"VehicleHistoricoController",
"VCReadOnlyController",
"TablasTelefonosJurisdiccionalesAccGridController",
"TablasTelefonosJuridiccionaesAccHelperController",
"SPReadOnlyController",
"SPEventoVideoController",
"SoftguardZonaFormController",
"SoftguardZonaController",
"SoftguardUsuarioGridController",
"SoftguardUsuarioFormController",
"SoftguardTestController",
"SoftguardSmsFormController",
"SoftguardSmsController",
"SoftguardPanelGridController",
"SoftguardPanelController",
"SoftguardNotaController",
"SoftguardMedicoFormController",
"SoftguardHorarioFormController",
"SoftguardFalsaController",
"SoftguardEstadoController",
"SoftguardContactoGridController",
"SoftguardContactoFormController",
"SmsRecibidosGridController",
"SmsGridController",
"SmsEnvioFormController",
"SmsConmutadosGridController",
"SmsAWCCGridController",
"SMPAttachGridController",
"SmartTrackMonitoreoController",
"SmartTrackGridController",
"SmartPanicsMonitoreoController",
"SmartpanicsHelperController",
"SmartPanicGridController",
"SmartMailProgramGridController",
"SmartMailFormController",
"ServTecReclamosGridController",
"ServTecReclamosFormController",
"ServTecPanelController",
"ServTecObservacionesGridController",
"ServTecHistoricoGridController",
"ServTecGridController",
"ServTecFullFormController",
"SerTecROController",
"SelecterHelperController",
"RutaGridController",
"ReporteMulticuentaController",
"ReporteGraficoController",
"ReporteEventosController",
"ReporteServTecController",
"ProcesarPorLoteController",
"PPushQueueGridController",
"PoiGridController",
"PasswordFormController",
"ParticionFormEditController",
"ParticionFormController",
"ParticionesGridController",
"ParticionesCopyFormController",
"ParticionesChooserController",
"OrganizationCuentaGridController",
"OrdenServTecController",
"MultimediaGridController",
"MultimediaEventosPanelController",
"MulticuentaZonasGridController",
"MulticuentaZonaCuentaFormController",
"MulticuentaServicioTecnicoGridController",
"MovilesGridController",
"ModuleController",
"ModuleTreeWRGuiadoController",
"MonitoreoGuiadoCargarObsController",
"MGOrganizationController",
"MGCuentaController",
"MGComprobantesGridController",
"MGClientHelperController",
"MGClientFormController",
"MedicoGridController",
"MapguardNewMovilController",
"MapguardMovilController",
"MapGuardGridController",
"MapGuardGpsController",
"MapGuardEventosController",
"MapguardCuentaController",
"MailFormController",
"m_usuariosFormController",
"m_cuentas_videoGridController",
"m_cuentas_videoFormController",
"m_cuentas_video_linksGridController",
"m_cuentas_video_linksFormController",
"m_cuenta_videoPanelController",
"LlamadaTelefonosDealerGridController",
"LlamadasSmartpanicsGridController",
"LlamadasReaFullGridController",
"LlamadasJuridiccionalesGridController",
"LlamadaRealizadasGridController",
"LlamadaHelperController",
"LlamadaGridController",
"LlamadaContactarGridController",
"LinkUrlGridController",
"ImagePanelController",
"ImagenesController",
"HorarioToleranciaController",
"HorarioExcepcionController",
"HorarioController",
"HorarioAlternativoController",
"GeocercaGridController",
"GeneradorEventoFormController",
"FlotaGridController",
"FlotaGpsController",
"EventSmsController",
"EventSelecterHelperController",
"EventRepAutController",
"EventProcesamientoController",
"EventPhoneController",
"EventoTimeLineFullController",
"EventosTrGridController",
"EventosPendientesTrGridController",
"EventoSonidoController",
"EventoReCategorizacionFormController",
"EventoMonitoreoController",
"EventoMonitoreoGuiadoController",
"EventoFormController",
"EventoController",
"EventObservacionesFormController",
"EventObservacionesController",
"EventImagesController",
"EstadoPruebaFormController",
"EstadoItemController",
"DocumentosFileGridController",
"DispositivoMovilWidgetController",
"DealerMultiSelecHelpController",
"CuentaROController",
"CuentaReporteController",
"CuentaRecepcionController",
"CuentaLocalizationGridController",
"CuentaImagenController",
"CuentaHelperControllerBAK",
"CuentaGridController",
"CuentaFormController",
"CuentaEventosPendientesController",
"CuentaController",
"ComandosGpsConfigController",
"ComandosEnviadosGridController",
"ComandoGpsSendController",
"BitacoraController",
"AwccUsuariosByCuentaGridController",
"AutomonitoreoFormController",
"AsignarTecnicoController",
"SoftguardUsuarioGrid2Controller",
"AwccDiyuntorController",
"ExAwccUsuarioByDealerGridController",
"AwccUsusarioByDealerGridController",
"AwccUsuariosByCuentaFormController",
"AwccUsuarioFromController",
"OrganizationHelperController",
"OrganizationFormController",
"ModoEmergenciaEventosController",
"EventObservacionesFormGuiadoController",
"SmartMailController",
"SmartMailTemplateGridController",
"SmartMailTemplateDatosController",
"SmartMailSenderGridController",
"SmartMailSenderFormController",
"CuentaResolucionesController",
"CuentaResolucionFormController"

],
UserData: _UserData,
quickTips: false,
platformConfig:{
    desktop:{
        quickTips: true,
    },
},

    requires: [
        "WebRemoto.*",
        "Ext.Responsive",
        "Common.*"
    ],

    launch: function() {
        console.log(arguments);
    },
    mainView: "WebRemoto.view.MetadataViewport",

    onAppUpdate: function() {
        Ext.Msg.confirm("Actualizacion detectada", "Reload?", function(choice) {
            if (choice === "yes")
            {
                window.location.reload();
            }
        });
    },
});