
var _uiApplicationName = "SgAppSerTec";
Ext.application({
    extend: "Common.Application",
    name: "SgAppSerTec",
    controllers: [
"AsignarMovilController",
"SerTecController",
"SerTecMapGpsController",
"ServTecMultiVsitasFormController",
"ServTecTecnicoProductosInsumidosController",
"TecguardAllSeguimientoMapController",
"TecguardDispSeguimientoMapController",
"TecGuardSeguimientoFormController",
"VigiControlMonitoreoController",
"VehicleSlaveGpsController",
"VCReadOnlyController",
"TaxonomyMasterTreeController",
"TablasTelefonosJurisdiccionalesAccGridController",
"TablasTelefonosJuridiccionaesAccHelperController",
"TablasInstaladoresGridController",
"STDepositoGridController",
"STDepositoFormController",
"SPReadOnlyController",
"SPEventoVideoController",
"SoftguardZonaController",
"SoftguardSmsFormController",
"SoftguardSmsController",
"SoftguardPanelGridController",
"SoftguardPanelController",
"SoftguardNotaController",
"SoftguardMedicoFormController",
"SoftguardEstadoController",
"SoftguardCuentaNewController",
"SoftguardContactoGridController",
"SoftguardContactoFormController",
"SmsRecibidosGridController",
"SmsGridController",
"SmsConmutadosGridController",
"SmartPanicsMonitoreoController",
"SmartMailProgramGridController",
"SmartMailController",
"ServTecVisitasGridController",
"ServTecVisitasFormController",
"ServTecTecnicoVisitasGridController",
"ServTecTabsController",
"ServTecReclamosGridController",
"ServTecReclamosFormController",
"ServTecProductosOrdenGridController",
"ServTecProductHelper",
"ServTecPanelController",
"ServTecAgendaController",
"ServTecObservacionesGridController",
"ServTecMovilVisitasGridController",
"ServTecMapFormController",
"ServTecHistoricoGridController",
"ServTecFullFormController",
"ServTecAsignacionStockController",
"SerTecROController",
"SelecterHelperController",
"ReporteServTecController",
"ProductGridController",
"PPushQueueGridController",
"OrdenServTecController",
"NotificacionesPanelController",
"MulticuentaServicioTecnicoGridController",
"ModuleController",
"MedicoGridController",
"MailFormController",
"m_stock_totalesGridController",
"m_stock_cabeceraGridController",
"m_stock_cabeceraFormController",
"LlamadasSmartpanicsGridController",
"LlamadasJuridiccionalesGridController",
"LlamadaRealizadasGridController",
"LlamadaHelperController",
"LlamadaGridController",
"LlamadaContactarGridController",
"LinkUrlGridController",
"GeocercaGridController",
"GeocercaFormController",
"EventSmsController",
"EventSelecterHelperController",
"EventRepAutController",
"EventProcesamientoController",
"EventPhoneController",
"EventoTimeLineFullController",
"EventoTimeLineController",
"EventoSonidoController",
"EventoFormController",
"EventoController",
"EventObservacionesFormController",
"EventObservacionesController",
"EventImagesController",
"EstadoItemController",
"DocumentosFileGridController",
"DepositosPanelController",
"DealerHelperController",
"CuentaReporteController",
"CuentaRecepcionController",
"CuentaHelperControllerBAK",
"CuentaGridController",
"CuentaFormController",
"CuentaController",
"BitacoraController",
"AutomonitoreoFormController",
"AsignarTecnicoController",
"ServTecReclamoController",
"CuentaResolucionesController",
"CuentaResolucionFormController",
"HorarioController",
"SoftguardHorarioFormController",
"HorarioAlternativoController",
"HorarioExcepcionController",
"HorarioExcepcionFormController",
"HorarioToleranciaController",
"FormularioSerTecEditHtmlGridController",
"FormularioSerTecHTMLEditorFormController",
    ],
    quickTips: false,
    platformConfig:{
        desktop:{
            quickTips: true,
        },
    },

    requires: [
        "SgAppSerTec.*",
        "Ext.Responsive",
        "Common.*",
    ],

    launch: function() {
        console.log(arguments);
    },
    mainView: "SgAppSerTec.view.MetadataViewport",

    onAppUpdate: function() {
        Ext.Msg.confirm("Actualizacion detectada", "Reload?", function(choice) {
            if (choice === "yes")
            {
                window.location.reload();
            }
        });
    },
});