IF SCHEMA_ID(N'dbo') IS NULL
    EXEC('CREATE SCHEMA [dbo]');
GO

CREATE TABLE [dbo].[m_st_cabecera] (
    [stc_iid] int NOT NULL,
    [stc_iid_cuenta] int NOT NULL,
    [stc_inumero] int NOT NULL,
    [stc_ctipo_servicio] char(3) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_ctipo_servicio] DEFAULT ('000') NOT NULL,
    [stc_mobservaciones] text COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_mobservaciones] DEFAULT ('') NOT NULL,
    [stc_dfecha_desde_1] datetime CONSTRAINT [DF_m_st_cabecera_stc_dfecha_desde_1] DEFAULT (getdate()) NOT NULL,
    [stc_dfecha_hasta_1] datetime CONSTRAINT [DF_m_st_cabecera_stc_dfecha_hasta_1] DEFAULT (getdate()) NOT NULL,
    [stc_dfecha_desde_2] datetime NOT NULL,
    [stc_dfecha_hasta_2] datetime NOT NULL,
    [stc_dfecha_desde_3] datetime NOT NULL,
    [stc_dfecha_hasta_3] datetime NOT NULL,
    [stc_dfecha_cierre] datetime NOT NULL,
    [stc_ccontacto] char(30) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_ccontacto] DEFAULT ('') NOT NULL,
    [stc_nestado] numeric(1,0) CONSTRAINT [DF_m_st_cabecera_stc_nestado] DEFAULT ((1)) NOT NULL,
    [stc_ctecnico_1] char(3) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_ctecnico_1] DEFAULT ('') NOT NULL,
    [stc_ctecnico_2] char(3) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_ctecnico_2] DEFAULT ('') NOT NULL,
    [stc_ctecnico_3] char(3) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_ctecnico_3] DEFAULT ('') NOT NULL,
    [stc_ctecnico_4] char(3) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_ctecnico_4] DEFAULT ('') NOT NULL,
    [stc_ctecnico_5] char(3) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_ctecnico_5] DEFAULT ('') NOT NULL,
    [stc_yValor] money CONSTRAINT [DF_m_st_cabecera_stc_yValor] DEFAULT ((0)) NOT NULL,
    [stc_nreclamo_1] numeric(1,0) CONSTRAINT [DF_m_st_cabecera_stc_nreclamo_1] DEFAULT ((0)) NOT NULL,
    [stc_creclamo_1] varchar(max) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_creclamo_1] DEFAULT ('') NOT NULL,
    [stc_nreclamo_2] numeric(1,0) CONSTRAINT [DF_m_st_cabecera_stc_nreclamo_2] DEFAULT ((0)) NOT NULL,
    [stc_creclamo_2] varchar(50) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_creclamo_2] DEFAULT ('') NOT NULL,
    [stc_nreclamo_3] numeric(1,0) CONSTRAINT [DF_m_st_cabecera_stc_nreclamo_3] DEFAULT ((0)) NOT NULL,
    [stc_creclamo_3] varchar(50) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_creclamo_3] DEFAULT ('') NOT NULL,
    [stc_nreclamo_4] numeric(1,0) CONSTRAINT [DF_m_st_cabecera_stc_nreclamo_4] DEFAULT ((0)) NOT NULL,
    [stc_creclamo_4] varchar(50) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_creclamo_4] DEFAULT ('') NOT NULL,
    [stc_nreclamo_5] numeric(1,0) CONSTRAINT [DF_m_st_cabecera_stc_nreclamo_5] DEFAULT ((0)) NOT NULL,
    [stc_creclamo_5] varchar(50) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_creclamo_5] DEFAULT ('') NOT NULL,
    [stc_cmovil_1] char(3) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_cmovil_1] DEFAULT ('') NOT NULL,
    [stc_cmovil_2] char(3) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_cmovil_2] DEFAULT ('') NOT NULL,
    [stc_dfecha_modificacion] datetime CONSTRAINT [DF_m_st_cabecera_stc_dfecha_modificacion] DEFAULT (getdate()) NOT NULL,
    [stc_ioperador] int CONSTRAINT [DF_m_st_cabecera_stc_ioperador] DEFAULT ((0)) NOT NULL,
    [stc_minsumos] text COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_minsumos] DEFAULT ('') NOT NULL,
    [stc_dintecnico_1] datetime NOT NULL,
    [stc_doutecnico_1] datetime NOT NULL,
    [stc_dintecnico_2] datetime NOT NULL,
    [stc_doutecnico_2] datetime NOT NULL,
    [stc_dintecnico_3] datetime NOT NULL,
    [stc_doutecnico_3] datetime NOT NULL,
    [stc_cdeposito] char(3) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_cdeposito] DEFAULT ('') NOT NULL,
    [stf_dfecha_vto_orden] datetime CONSTRAINT [DF_m_st_cabecera_stf_dfecha_vto_orden] DEFAULT (getdate()) NOT NULL,
    [stc_dsalida_al_cliente_DSS] datetime NOT NULL,
    [stc_darribo_al_cliente_DSS] datetime NOT NULL,
    [stc_dsalida_desde_cliente_DSS] datetime NOT NULL,
    [stc_iforma_viaje_DSS] int NOT NULL,
    [stc_cconformidad_html] varchar(max) COLLATE Modern_Spanish_CI_AS CONSTRAINT [DF_m_st_cabecera_stc_cconformidad_html] DEFAULT ('') NOT NULL,
    [stc_idOrigenOrden] int CONSTRAINT [DF_m_st_cabecera_stc_idOrigenOrden] DEFAULT ((0)) NOT NULL,
    [stc_iusuarioDss] int NOT NULL,
    [stc_dfecha_creacion] datetime CONSTRAINT [DF_m_st_cabecera_stc_dfecha_creacion] DEFAULT (getdate()) NOT NULL,
    [stc_nvalorpagotecnico] money NOT NULL,
    [stc_ncostomanodeobra] money NOT NULL,
    [stc_dfechapago] date NOT NULL,
    [stc_iPrioridad] int CONSTRAINT [DF_m_st_cabecera_stc_iPrioridad] DEFAULT ((1)) NOT NULL,
    [stc_iOrganizacion] int CONSTRAINT [DF_m_st_cabecera_stc_iOrganizacion] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_m_st_cabecera] PRIMARY KEY CLUSTERED ([stc_iid] ASC)
);
GO

CREATE NONCLUSTERED INDEX [NC_STCab_CtaEstado] ON [dbo].[m_st_cabecera] ([stc_iid_cuenta] ASC, [stc_nestado] ASC);
GO
