
var _uiApplicationName = "WebMG";
Ext.application({
    extend: "Common.Application",
    name: "WebMG",
    controllers: [
"ClienteFormController",
"ComprobanteItemManualFormController",
"ComprobantesDePagoGridController",
"CuentaCorrientePanelController",
"FacturacionAutomaticaGridController",
"FacturacionAutomaticaWizardController",
"FacturaPrintController",
"ExportTxtFormController",
"mg_informacionPagoFormController",
"mg_maestrocuentasFormController",
"mg_maestrocuentasGridController",
"OrganizationMGController",
"PagoFormController",
"PagoGridController",
"RemesaExportFormController",
"t_novedades_fcFormController",
"WebMGController",
"TaxonomyTreeController",
"TaxonomyMasterTreeController",
"TaxonomyManagerController",
"TablasTelefonosJurisdiccionalesAccGridController",
"TablasTelefonosJuridiccionaesAccHelperController",
"t_novedades_fcGridController",
"STProductosGridController",
"STProductosFormController",
"SPEventoVideoController",
"SoftguardZonaFormController",
"SoftguardZonaController",
"SoftguardUsuarioGridController",
"SoftguardUsuarioFormController",
"SoftguardTestController",
"SoftguardSmsFormController",
"SoftguardSmsController",
"SoftguardPanelController",
"SoftguardNotaController",
"SoftguardMedicoFormController",
"SoftguardHorarioFormController",
"SoftguardFalsaController",
"SoftguardEstadoController",
"SMPAttachGridController",
"ServTecGridController",
"SelecterHelperController",
"ProductoListaPreciosController",
"ProductHelperController",
"PersonHelperController",
"PersonGridController",
"PersonFormController",
"PersonController",
"PasswordFormController",
"ParticionFormEditController",
"ParticionFormController",
"ParticionesGridController",
"ParticionesCopyFormController",
"ParticionesChooserController",
"OrganizationHelperController",
"OrganizationGridController",
"OrganizationFormController",
"OrganizationCuentaRangoController",
"OrganizationCuentaGridController",
"OrderPrintController",
"OrderItemGridController",
"OrderItemFormController",
"OrderGridController",
"OrderFormController",
"OrderController",
"NotificacionesGridController",
"ModuleController",
"MGOrganizationController",
"MGCuentaController",
"MGComprobantesGridController",
"MGClientHelperController",
"MGClientFormController",
"MG_MovientosCuentasController",
"mg_listas_preciosGridController",
"MailActionFormController",
"ListasPreciosFromController",
"ImpuestosHelperController",
"ImpuestoItemGridController",
"ImpuestoItemFormController",
"FormBuilderHelperController",
"FormBuilderEditHelperController",
"EventGridController",
"EventFormController",
"EventController",
"EstadoItemController",
"DocumentosFileGridController",
"CuentasSinContratoGridController",
"CuentaHelperControllerBAK",
"CuentaFormController",
"CuentaController",
"ContratoTemplateGridController",
"ContratoTemplateFormController",
"ContratoTabPanelController",
"ContratosFacturaController",
"ContratoItemGridController",
"ContratoItemFormController",
"ContratoGridController",
"ContratoFormController",
"ContratoCuentaGridController",
"ComprobanteItemGridController",
"ComprobanteItemFormController",
"ComprobanteGridController",
"ComprobanteFormController",
"BitacoraController",
"AwccUsusarioByDealerGridController",
"AwccUsuariosByCuentaGridController",
"AwccUsuariosByCuentaFormController",
"AwccUsuarioFromController",
"AwccDiyuntorController",
"AvisoProgramadoTemplateFormController",
"AvisoProgramadoHelperController",
"AvisoProgramadoGridController",
"AutomonitoreoFormController",
"ActionGridController",
"ActionFormController",
"SoftguardCuentaNewController",
"DealerHelperController"

    ],
    UserData: typeof _UserData !== "undefined" ? _UserData : null,
    quickTips: false,
    platformConfig:{
        desktop:{
            quickTips: true,
        },
    },

    requires: [
        "WebMG.*",
        "Ext.Responsive",
        "Common.*",
    ],

    launch: function() {
        console.log(arguments);
    },
    mainView: "WebMG.view.MetadataViewport",

    onAppUpdate: function() {
        Ext.Msg.confirm("Actualizacion detectada", "Reload?", function(choice) {
            if (choice === "yes")
            {
                window.location.reload();
            }
        });
    },
});